### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zQueal** [codesoap/atto#16] opened 2023-05-22 09:44 UTC
```
$ echo $SEED | atto -a 0 b
Error: json: cannot unmarshal array into Go struct field internalPending.blocks of type map[string]atto.pendingBlock
```

I've tried to troubleshoot but the best I can figure the offending bug is somewhere here;

https://github.com/codesoap/atto/blob/ee338fbf358690f249197eb2d29ade720572ad92/pending.go#L19-L47

**Comment by zQueal** [comment] 2023-05-23 04:46
Seems interesting, the JSON formatting looks fine;

```cmd
{
    "frontier": "",
    "open_block": "",
    "representative_block": "",
    "balance": "",
    "modified_timestamp": "",
    "block_count": "",
    "account_version": "",
    "confirmation_height": "",
    "confirmation_height_frontier": "",
    "balance_nano": "",
    "username": ""
}
```

**Comment by codesoap** [comment] 2023-05-23 06:49
Thanks for chiming in, @nano2dev! I have tested the problematic requests with your node and was able to reproduce the problem. When there are pending blocks/receivables, the response is as expected:

```
$ curl -s -H 'Content-Type: application/json' \
    -d '{
        "action": "pending",
        "account": "nano_3zxjpc798ts7ist3wuzp1wx8rbawpgf9ysoz91khjigubdj435ss7k4bubac",
        "include_only_confirmed": "true",
        "source": "true"
    }' https://rpc.nano.to | jq .
{
  "deprecated": "1",
  "blocks": {
    "8C7C28AD6CE62A1BF7B419F0898047E7E7E6BE895FC4104DCEBD34FA3FE92D72": {
      "amount": "100000000000000000000000000000",
      "source": "nano_1b6st6e5duu763g9m5px5jfhjesw6hdbceka8pg5fxn58fhucqy1u9wsapir"
    }
  }
}
```

However, if there is nothing to receive, `blocks` is an empty array (`[]`) instead of an empty object (`{}`). This seems like a bug to me since `"source": "true"` was requested:

```
curl -s -H 'Content-Type: application/json' \
    -d '{
        "action": "pending",
        "account": "nano_3zxjpc798ts7ist3wuzp1wx8rbawpgf9ysoz91khjigubdj435ss7k4bubac",
        "include_only_confirmed": "true",
        "source": "true"
    }' https://rpc.nano.to | jq .
{
  "deprecated": "1",
  "blocks": []
}
```

What software are you running your node with? Is it https://github.com/nanocurrency/nano-node ? I want to report this bug.

**Comment by codesoap** [comment] 2023-05-23 16:03
@nano2dev I think we have a misunderstanding. The response to the `pending`/`receivable` action should indeed contain an array below `blocks` for "regular" requests. However, as you can see in the (first) example of my previous comment and in the [documentation](https://docs.nano.org/commands/rpc-protocol/#receivable), when `"source": "true"` is specified in the request, the response should **not** contain an array below `blocks`, but an object instead.

Am I understanding it correctly, that you have explicitly configured your node to deviate from the behavior of the official node, https://github.com/nanocurrency/nano-node ?

**Comment by codesoap** [comment] 2023-05-23 21:20
@zQueal I'm closing this issue for now. Esteban has explained that the bug stems from a modification to the protocol, that he has made for his node. I don't want to support inofficial RPC responses in atto, so I'm afraid that https://rpc.nano.to/ is not a good node to use with atto.

If you still want to use this node, you can apply this patch to your version of atto and everything should work again: bdb6338c264b8baadcc8c256fb68623b7aa94b73

**Closed by codesoap** 2023-05-23 21:20 UTC

**Comment by zQueal** [comment] 2023-05-23 22:11
I appreciate the patch (and wil use it for testing), but I have to agree. Deviating from the official protocol is too dangerous for anything other than testing.

Thanks for your time.

**Comment by zQueal** [comment] 2023-05-24 04:04
Not really sure what the hostility is for...everyone is perfectly cognizant of what an RPC proxy is. But even your website says specifically "PUBLIC NANO NODE" and not "PUBLIC NANO PROXY" so you'll have to excuse the confusion... In the end you're altering the accepted and default schema sent by the node through your proxy, which causes bugs for people not expecting that behavior. As clearly evidenced here. It's your right to do, but you go through great lengths to confuse your end users--even saying explicitly that they're interfacing with a node. 🤷🏻‍♂️

But this really isn't the place for that kind of discussion, I guess. I appreciate the service.
